export const boardActions = {
    CREATE_BOARD:"CREATE_BOARD",   
    CREATE_LIST: "CREATE_LIST",
    CREATE_CARD:"CREATE_CARD",
    MOVE_CARD:"MOVE_CARD",
    ADD_CHECK_LIST:"ADD_CHECK_LIST",
    TOGGLE_CHECK_LIST:"TOGGLE_CHECK_LIST",
}